### PR TITLE
Removed TFS settings from .gitignore

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
#first

### CODE REVIEW

**Comment by FindingNamo** [comment]
Lol!

**Comment by FindingNamo** [comment]
BTW @JoshuaKGoldberg, if you're curious, it all ended up meshing nicely!

https://test-travisci-2-heroku.herokuapp.com (let it load... slow cuz free so it needs to wake up since not dedicated)

push to gh -> starts build and test in travis -> if successful -> autodeploy to heroku

**Comment by JoshuaKGoldberg** [comment]
I have no idea what this is

**Comment by JoshuaKGoldberg** [comment]
oh OH this is cool !

**Pull request merged**
